import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Cleaning database...");
  await prisma.recipeIngredient.deleteMany({});
  await prisma.ingredient.deleteMany({});
  await prisma.savedRecipe.deleteMany({});
  await prisma.mealEntry.deleteMany({});
  await prisma.meal.deleteMany({});
  await prisma.nutritionLog.deleteMany({});
  await prisma.plannedMeal.deleteMany({});
  await prisma.groceryItem.deleteMany({});
  await prisma.groceryList.deleteMany({});
  await prisma.waterLog.deleteMany({});
  await prisma.moodLog.deleteMany({});
  await prisma.userAchievement.deleteMany({});
  await prisma.mealTemplateItem.deleteMany({});
  await prisma.mealTemplate.deleteMany({});
  await prisma.bloomScore.deleteMany({});
  await prisma.insight.deleteMany({});
  await prisma.recipe.deleteMany({});

  console.log("Seeding expanded recipes and ingredients...");

  const recipesData = [
    {
      title: "Artisanal Avocado Toast",
      summary: "Experience a luxurious, nutrient-dense breakfast masterpiece that elevates the simple avocado toast to a fine-dining experience. We start with thick, hand-carved slices of rustic, artisanal whole-grain sourdough bread, naturally leavened and fermented for 24 hours to promote optimal gut health and ease digestion. The bread is toasted to a crisp, golden perfection, providing a crunchy contrast to the velvety layer of freshly mashed, premium-grade organic Hass avocados. The avocado mash is seasoned to perfection with cold-pressed organic lemon juice, coarse Himalayan pink salt, and freshly cracked black peppercorns. We crown this beautiful creation with half-cut heirloom cherry tomatoes bursting with sweet, vine-ripened flavor, alongside nutrient-dense raw pumpkin seeds and organic sunflower seeds that offer a crunch rich in zinc, magnesium, and vitamin E. Finally, it is garnished with delicate organic microgreens, micro-cilantro, and a light dusting of red pepper flakes for a subtle, warming kick. This breakfast classic is meticulously balanced to provide high-quality complex carbohydrates, gut-supportive dietary fiber, and monounsaturated fatty acids that support cardiovascular health and keep you feeling energized and satiated throughout the morning.",
      image: null,
      instructions: "1. Carefully slice a fresh loaf of artisanal whole-grain sourdough bread into thick, even slices (about 3/4 inch thick). Place them in a toaster or grill on a cast-iron skillet over medium-high heat until the edges are beautifully charred and the center is warm and toasted to golden perfection.\n2. Slice a ripe, organic Hass avocado in half, remove the pit safely, and scoop the rich, green flesh into a clean marble pestle or mixing bowl. Squeeze fresh organic lemon juice directly over the avocado to enhance the flavor profile and prevent oxidation. Add a pinch of coarse Himalayan pink salt and freshly cracked black pepper.\n3. Using a fork or pestle, gently mash the avocado, leaving some chunks for texture. Avoid over-blending to preserve the artisanal, rustic mouthfeel.\n4. Wash and slice vine-ripened heirloom cherry tomatoes into clean halves.\n5. Spread the velvety mashed avocado mixture evenly across the warm sourdough slices, ensuring it reaches every edge.\n6. Artfully arrange the tomato halves on top of the avocado bed.\n7. Generously scatter raw pumpkin seeds and sunflower seeds across the top to add texture and essential micronutrients.\n8. Finish with a delicate garnish of fresh microgreens, micro-cilantro, and a light sprinkle of crushed red pepper flakes. Serve immediately while the bread is warm and crisp.",
      servings: 1,
      readyInMinutes: 12,
      cuisines: JSON.stringify(["American"]),
      diets: JSON.stringify(["Vegan", "Vegetarian"]),
      tags: JSON.stringify(["breakfast", "quick", "healthy"]),
      calories: 280,
      protein: 8,
      carbs: 24,
      fat: 18,
      fiber: 7,
      sugar: 3,
      ingredients: [
        { name: "Organic Hass Avocado", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Artisanal Whole Grain Sourdough Bread", amount: 2, unit: "slice", aisle: "Bakery" },
        { name: "Organic Heirloom Cherry Tomatoes", amount: 6, unit: "count", aisle: "Produce" },
        { name: "Fresh Organic Lemon Juice", amount: 1, unit: "tsp", aisle: "Produce" },
        { name: "Organic Raw Pumpkin Seeds", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Raw Sunflower Seeds", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Organic Microgreens", amount: 0.25, unit: "cup", aisle: "Produce" },
      ],
    },
    {
      title: "Herb-Marinated Grilled Chicken Salad",
      summary: "A clean, high-protein Mediterranean-inspired culinary masterpiece designed to fuel muscle synthesis, metabolic health, and clean cellular energy. At the core is premium, organic, hormone-free chicken breast, tenderly marinated in a bouquet of wild rosemary, thyme, oregano, and minced garlic before being grilled over medium-high heat to lock in its natural juices. The chicken is sliced into tender strips and laid over a crisp, vibrant bed of organic romaine hearts and tender baby spinach leaves, selected for their high folate and iron content. We toss this green canvas with crunchy English cucumber half-moons, vine-ripened sweet cherry tomatoes, and kalamata olives for a rich dose of healthy fats. It is crowned with crumbled authentic Greek sheep's milk feta cheese and drizzled with a light, house-made emulsified vinaigrette made of cold-pressed extra virgin olive oil, fresh lemon juice, raw honey, and dijon mustard. This low-glycemic, high-protein salad delivers a dense supply of essential amino acids, powerful antioxidants, and anti-inflammatory monounsaturated fats.",
      image: null,
      instructions: "1. In a bowl, prepare the chicken marinade by whisking together olive oil, minced garlic, dried rosemary, thyme, oregano, salt, and pepper. Place the organic chicken breast in the marinade and let it rest for at least 30 minutes in the refrigerator to absorb all the aromatics.\n2. Heat a cast-iron grill pan or outdoor grill to medium-high heat. Place the marinated chicken breast on the grill and sear for 6 to 7 minutes on each side. Ensure the internal temperature reaches 165°F (74°C) to lock in the juices while guaranteeing safety. Remove the chicken from the heat and let it rest on a cutting board for 5 minutes before slicing into thin, clean diagonal strips.\n3. While the chicken is cooking, wash and thoroughly dry the organic romaine hearts and baby spinach leaves. Chop the romaine into bite-sized pieces and toss with the baby spinach in a large wooden salad bowl.\n4. Rinse and cut the cucumber into half-moons. Slice the cherry tomatoes in half.\n5. Prepare the dressing by whisking cold-pressed extra virgin olive oil, freshly squeezed lemon juice, a teaspoon of Dijon mustard, a touch of raw honey, and a pinch of salt.\n6. Add the sliced cucumber, cherry tomatoes, and kalamata olives to the greens. Drizzle the lemon-herb vinaigrette over the salad and toss gently to coat the leaves evenly.\n7. Top the salad with the warm, sliced grilled chicken breast and sprinkle crumbled Greek feta cheese over the top. Garnish with a crack of fresh black pepper and serve immediately.",
      servings: 1,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Mediterranean", "American"]),
      diets: JSON.stringify(["Gluten Free", "High Protein"]),
      tags: JSON.stringify(["lunch", "salad", "high-protein"]),
      calories: 420,
      protein: 42,
      carbs: 12,
      fat: 22,
      fiber: 4,
      sugar: 5,
      ingredients: [
        { name: "Organic Boneless Chicken Breast", amount: 150, unit: "grams", aisle: "Meat" },
        { name: "Organic Romaine Hearts", amount: 2, unit: "cups", aisle: "Produce" },
        { name: "Organic Baby Spinach", amount: 1, unit: "cup", aisle: "Produce" },
        { name: "English Cucumber", amount: 0.5, unit: "count", aisle: "Produce" },
        { name: "Vine-Ripened Cherry Tomatoes", amount: 8, unit: "count", aisle: "Produce" },
        { name: "Cold-Pressed Extra Virgin Olive Oil", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Organic Lemon Vinaigrette", amount: 2, unit: "tbsp", aisle: "Pantry" },
        { name: "Sheep's Milk Feta Cheese", amount: 30, unit: "grams", aisle: "Dairy" },
        { name: "Kalamata Olives", amount: 6, unit: "count", aisle: "Canned Goods" },
      ],
    },
    {
      title: "Vibrant Quinoa & Sweet Potato Buddha Bowl",
      summary: "A colorful, meticulously structured plant-based power bowl designed to optimize digestion, balance hormones, and deliver sustained, slow-burning complex energy. This nourishing bowl is anchored by a generous serving of fluffy, organic tri-color quinoa—a complete plant protein containing all nine essential amino acids—steamed in a clean vegetable broth. We layer it with fresh, organic baby spinach and tender steamed kale. Next, we add caramelized, roasted sweet potato cubes spiced with anti-inflammatory ground turmeric, smoked paprika, and cumin, alongside crispy, high-fiber roasted chickpeas. The bowl is balanced with half a sliced Haas avocado for creamy texture and heart-healthy monounsaturated fats. A rich, silky dressing made from roasted sesame tahini, fresh lemon juice, garlic, and water is drizzled over the top, introducing a nutty richness loaded with calcium and healthy fats. This vegan, gluten-free dish is an absolute powerhouse of dietary fiber, minerals, and plant-based macronutrients.",
      image: null,
      instructions: "1. Thoroughly rinse the tri-color quinoa under cold water to remove any bitter saponins. In a medium saucepan, combine the quinoa with organic vegetable broth in a 1:2 ratio. Bring to a boil, then reduce heat to low, cover, and let simmer for 15 minutes. Remove from heat and let sit covered for 5 minutes before fluffing with a fork.\n2. Preheat the oven to 400°F (200°C). Peel and chop the sweet potato into 1/2-inch cubes. Rinse and drain the canned chickpeas, patting them completely dry with a paper towel. In a bowl, toss both the sweet potato cubes and chickpeas with a tablespoon of olive oil, ground cumin, smoked paprika, turmeric, sea salt, and black pepper.\n3. Spread the sweet potatoes and chickpeas in a single layer on a parchment-lined baking sheet. Roast in the preheated oven for 25 to 30 minutes, tossing halfway through, until the sweet potatoes are tender and caramelized and the chickpeas are crispy and golden.\n4. Prepare the tahini dressing: In a small bowl, whisk together the sesame tahini, fresh lemon juice, minced garlic, and a pinch of salt. Slowly whisk in warm water, one tablespoon at a time, until the dressing reaches a smooth, pourable consistency.\n5. Assemble the bowls: Divide the fresh baby spinach and cooked quinoa between two wide serving bowls.\n6. Arrange the roasted sweet potatoes, crispy chickpeas, and sliced avocado in separate sections on top of the quinoa bed.\n7. Drizzle the creamy tahini dressing generously over the entire bowl. Garnish with a sprinkle of black sesame seeds or microgreens if desired, and serve warm.",
      servings: 2,
      readyInMinutes: 40,
      cuisines: JSON.stringify(["Global"]),
      diets: JSON.stringify(["Vegan", "Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "lunch", "meal-prep"]),
      calories: 550,
      protein: 16,
      carbs: 72,
      fat: 24,
      fiber: 12,
      sugar: 8,
      ingredients: [
        { name: "Organic Tri-Color Quinoa", amount: 1, unit: "cup", aisle: "Pantry" },
        { name: "Organic Sweet Potato", amount: 1, unit: "large", aisle: "Produce" },
        { name: "Organic Chickpeas (Garbanzo Beans)", amount: 1, unit: "can", aisle: "Canned Goods" },
        { name: "Organic Baby Spinach", amount: 2, unit: "cups", aisle: "Produce" },
        { name: "Roasted Sesame Tahini", amount: 2, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Haas Avocado", amount: 0.5, unit: "count", aisle: "Produce" },
        { name: "Organic Olive Oil", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Lemon Juice", amount: 1.5, unit: "tbsp", aisle: "Produce" },
      ],
    },
    {
      title: "Wild Berry & Whey Protein Smoothie",
      summary: "An incredibly refreshing, silky-smooth protein shake formulated to accelerate post-workout muscle recovery, combat oxidative stress, and support skin, joint, and gut health. This delicious smoothie combines a powerful blend of antioxidant-packed frozen wild blueberries, sweet organic strawberries, and tart red raspberries. We add half a potassium-rich organic banana for natural sweetness and electrolyte balance, blended with cold unsweetened organic almond milk. We fortify this blend with a scoop of premium grass-fed whey protein isolate to repair muscle tissues, and a tablespoon of fiber-dense organic chia seeds that swell to support digestive health and supply essential Omega-3 fatty acids. This vibrant, purple-hued beverage delivers clean, crash-free energy and is rich in Vitamin C, prebiotic fibers, and clean amino acids, making it the perfect post-workout fuel or active meal replacement.",
      image: null,
      instructions: "1. Pour the cold unsweetened almond milk into the jar of a high-speed blender first; adding liquid first prevents the dry protein powder from sticking to the blades.\n2. Add the frozen wild blueberries, organic strawberries, and raspberries to the blender. The frozen fruit gives the smoothie a thick, frosty texture without needing ice.\n3. Add the half banana, which provides creaminess and a smooth mouthfeel.\n4. Add a scoop of premium grass-fed whey protein isolate (or plant-based protein powder if preferred) and the organic chia seeds.\n5. Secure the blender lid and blend on low speed for 15 seconds, then gradually increase the speed to high. Blend on high for 1 to 2 minutes until all the seeds, berries, and powders are emulsified into a velvety, uniform consistency.\n6. Pour the smoothie into a tall glass, garnish with a sprinkle of whole chia seeds or a fresh strawberry on the rim, and enjoy immediately for optimal nutrient absorption.",
      servings: 1,
      readyInMinutes: 6,
      cuisines: JSON.stringify(["American"]),
      diets: JSON.stringify(["Vegetarian", "High Protein", "Gluten Free"]),
      tags: JSON.stringify(["breakfast", "snack", "smoothie"]),
      calories: 320,
      protein: 30,
      carbs: 35,
      fat: 6,
      fiber: 8,
      sugar: 18,
      ingredients: [
        { name: "Organic Frozen Wild Berries", amount: 1, unit: "cup", aisle: "Frozen" },
        { name: "Grass-Fed Whey Protein Isolate", amount: 1, unit: "scoop", aisle: "Supplements" },
        { name: "Unsweetened Organic Almond Milk", amount: 1.25, unit: "cups", aisle: "Dairy Alternative" },
        { name: "Organic Chia Seeds", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Banana", amount: 0.5, unit: "count", aisle: "Produce" },
      ],
    },
    {
      title: "Pan-Seared Salmon with Sweet Potato & Broccoli",
      summary: "An ultra-premium, nutrient-dense dinner plate designed to deliver a massive dose of cardioprotective Omega-3 fatty acids (EPA and DHA), high-quality complete protein, and slow-burning complex carbohydrates. The centerpiece is a fresh, wild-caught salmon fillet, seasoned with wild dill, sea salt, garlic powder, and lemon zest, pan-seared in a touch of avocado oil to achieve a crispy skin and a tender, flaky interior. It is served alongside a smooth, velvety mash of roasted sweet potatoes, rich in beta-carotene and Vitamin A, and fresh broccoli florets lightly steamed and sautéed with sliced garlic in cold-pressed extra virgin olive oil. This clean, anti-inflammatory meal is perfect for dinner, supporting metabolic recovery, brain health, and tissue repair.",
      image: null,
      instructions: "1. Remove the wild-caught salmon fillet from the refrigerator 15 minutes before cooking to bring it closer to room temperature, ensuring even cooking. Pat the skin and flesh completely dry with a paper towel. Season the flesh side with sea salt, black pepper, garlic powder, and fresh dill.\n2. Preheat the oven to 400°F (200°C). Scrub the sweet potato, poke it several times with a fork, and roast it whole in the oven for 40 to 45 minutes until completely tender. Once done, slice it open, scoop out the sweet flesh, and mash it in a bowl with a teaspoon of extra virgin olive oil and a pinch of salt until smooth and creamy.\n3. Cut the broccoli into medium florets. Steam the broccoli for 5 minutes until it turns a vibrant green color and is tender-crisp. In a small pan, heat a teaspoon of olive oil over low heat, add sliced garlic, and sauté for 1 minute until fragrant. Toss the steamed broccoli in the garlic oil for 1 minute.\n4. Heat avocado oil in a cast-iron skillet over medium-high heat. Once hot, place the salmon fillet in the pan, skin-side down. Press down gently with a spatula for 10 seconds to prevent curling. Sear for 4 to 5 minutes until the skin is incredibly crispy. Flip the fillet and cook for another 2 to 3 minutes until the salmon is cooked to medium-rare or medium. Remove from pan.\n5. Plate the salmon immediately next to the warm sweet potato mash and garlic-infused broccoli. Squeeze fresh lemon juice over the salmon before serving.",
      servings: 1,
      readyInMinutes: 35,
      cuisines: JSON.stringify(["American"]),
      diets: JSON.stringify(["Gluten Free", "High Protein"]),
      tags: JSON.stringify(["dinner", "healthy", "clean"]),
      calories: 510,
      protein: 38,
      carbs: 42,
      fat: 20,
      fiber: 8,
      sugar: 10,
      ingredients: [
        { name: "Wild-Caught Salmon Fillet", amount: 180, unit: "grams", aisle: "Seafood" },
        { name: "Organic Sweet Potato", amount: 1, unit: "large", aisle: "Produce" },
        { name: "Organic Broccoli Florets", amount: 1.5, unit: "cups", aisle: "Produce" },
        { name: "Cold-Pressed Extra Virgin Olive Oil", amount: 2, unit: "tsp", aisle: "Pantry" },
        { name: "Avocado Oil", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Fresh Lemon", amount: 0.5, unit: "count", aisle: "Produce" },
      ],
    },
    {
      title: "Greek Yogurt Parfait",
      summary: "A refreshing, gut-supportive, and high-protein breakfast or mid-day snack that perfectly balances creamy, tart, and crunchy elements. We layer thick, organic, unsweetened Greek yogurt—packed with active live cultures that feed the gut microbiome and provide clean calcium—with a vibrant assortment of fresh organic strawberries, wild blueberries, and blackberries. For a satisfying crunch, we add premium, honey-sweetened oat and almond granola that provides slow-digesting carbohydrates and healthy fats. It is crowned with a light drizzle of organic raw honey and a pinch of fresh mint leaves. This high-protein parfait supports bone density, digestive comfort, and sustained energy levels throughout the day.",
      image: null,
      instructions: "1. Gather a clean, tall glass or dessert bowl to showcase the beautiful layers of the parfait.\n2. Spoon half of the thick Greek yogurt (about 100g) into the bottom of the glass, smoothing the surface with the back of the spoon.\n3. Wash and slice the organic strawberries. Combine them with the fresh wild blueberries.\n4. Place a layer of the mixed berries directly over the Greek yogurt, followed by a generous sprinkle of the honey-almond granola.\n5. Spoon the remaining Greek yogurt on top to form the next layer.\n6. Add another layer of fresh berries and the remaining granola.\n7. Drizzle a tablespoon of raw organic honey over the top, allowing it to seep down through the layers.\n8. Garnish with a fresh sprig of mint and serve immediately to enjoy the crunchy texture of the granola before it softens.",
      servings: 1,
      readyInMinutes: 7,
      cuisines: JSON.stringify(["Greek", "Mediterranean"]),
      diets: JSON.stringify(["Vegetarian", "High Protein"]),
      tags: JSON.stringify(["breakfast", "snack", "quick"]),
      calories: 290,
      protein: 20,
      carbs: 38,
      fat: 6,
      fiber: 4,
      sugar: 22,
      ingredients: [
        { name: "Organic Unsweetened Greek Yogurt", amount: 200, unit: "grams", aisle: "Dairy" },
        { name: "Fresh Organic Strawberries", amount: 5, unit: "count", aisle: "Produce" },
        { name: "Fresh Wild Blueberries", amount: 0.25, unit: "cup", aisle: "Produce" },
        { name: "Honey-Almond Granola", amount: 0.25, unit: "cup", aisle: "Pantry" },
        { name: "Raw Organic Honey", amount: 1, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Crispy Sesame Tofu & Vegetable Stir-Fry",
      summary: "A colorful, nutrient-dense, and highly satisfying plant-based stir-fry featuring extra-firm organic tofu pan-seared to a golden, crispy texture. Tossed with a vibrant medley of fresh, fiber-rich vegetables, including sweet red bell pepper, crunchy broccoli florets, snap peas, and julienned carrots. Everything is cooked rapidly in a wok with toasted sesame oil, minced fresh ginger, and garlic, then glazed with a low-sodium tamari soy sauce. This dish is loaded with complete plant proteins, antioxidants, vitamins A and C, and essential minerals, offering a clean, energizing, and anti-inflammatory lunch or dinner.",
      image: null,
      instructions: "1. Cut the extra-firm tofu into 1-inch cubes. Lay them on a clean kitchen towel, place another towel on top, and put a heavy plate on it to press out excess moisture for 15 minutes. This is critical for getting the tofu crispy.\n2. Heat a tablespoon of toasted sesame oil in a large non-stick skillet or wok over medium-high heat. Add the tofu cubes and sear for 8 to 10 minutes, turning occasionally, until all sides are golden-brown and crispy. Transfer the tofu to a plate lined with paper towels.\n3. Cut the red bell pepper into thin strips, chop the broccoli into small florets, and trim the snap peas. Finely mince the garlic cloves and grate the fresh ginger.\n4. In the same skillet, add another teaspoon of sesame oil. Toss in the minced garlic and grated ginger, sautéing for 30 seconds until highly fragrant.\n5. Add the broccoli florets, bell peppers, carrots, and snap peas. Stir-fry rapidly on high heat for 4 to 5 minutes, adding a tablespoon of water if needed to steam-cook the broccoli, keeping them bright green and tender-crisp.\n6. Return the crispy tofu to the skillet. Pour in the low-sodium soy sauce (or tamari) and toss everything together for 1 to 2 minutes until the sauce glazes the ingredients.\n7. Transfer to plates, sprinkle with toasted sesame seeds and chopped green onions, and serve hot.",
      servings: 2,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Asian"]),
      diets: JSON.stringify(["Vegan", "Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["lunch", "dinner", "quick"]),
      calories: 340,
      protein: 18,
      carbs: 26,
      fat: 16,
      fiber: 6,
      sugar: 5,
      ingredients: [
        { name: "Organic Extra-Firm Tofu", amount: 250, unit: "grams", aisle: "Produce" },
        { name: "Organic Red Bell Pepper", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Organic Broccoli Florets", amount: 1, unit: "cup", aisle: "Produce" },
        { name: "Organic Sugar Snap Peas", amount: 0.75, unit: "cup", aisle: "Produce" },
        { name: "Low-Sodium Tamari Soy Sauce", amount: 2, unit: "tbsp", aisle: "Pantry" },
        { name: "Toasted Sesame Oil", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Garlic", amount: 2, unit: "cloves", aisle: "Produce" },
        { name: "Fresh Ginger", amount: 1, unit: "tsp", aisle: "Produce" },
      ],
    },
    {
      title: "Mediterranean Chickpea Salad",
      summary: "A bright, zesty, and refreshing combination of authentic Mediterranean flavors designed to support digestive health, steady blood sugar levels, and provide robust antioxidant protection. Plump, organic chickpeas (garbanzo beans) are tossed with crisp English cucumber, sweet organic cherry tomatoes, diced red onions, and kalamata olives. It is highlighted by crumbled Greek sheep's milk feta cheese, providing a rich, salty bite. The salad is dressed in an emulsified mixture of cold-pressed extra virgin olive oil, fresh lemon juice, and dried wild oregano. This naturally gluten-free and vegetarian salad is loaded with plant-based protein, prebiotic dietary fiber, and heart-healthy monounsaturated fats.",
      image: null,
      instructions: "1. Drain the canned chickpeas into a colander and rinse them thoroughly under cold running water to remove excess sodium. Let them drain completely.\n2. Wash the vegetables. Dice the English cucumber into small, even cubes. Cut the cherry tomatoes in half. Finely dice the red onion.\n3. In a large mixing bowl, combine the drained chickpeas, diced cucumber, cherry tomato halves, diced red onion, and kalamata olives.\n4. In a small mason jar or bowl, whisk together the cold-pressed extra virgin olive oil, freshly squeezed lemon juice, dried wild oregano, a pinch of sea salt, and black pepper until well emulsified.\n5. Pour the vinaigrette dressing over the salad ingredients and toss gently with a large spoon to ensure all components are evenly coated.\n6. Gently fold in the crumbled Greek sheep's milk feta cheese, taking care not to over-mix so the cheese doesn't turn mushy.\n7. Cover and let the salad sit in the refrigerator for 10 to 15 minutes before serving to allow the flavors to meld together beautifully. Garnish with chopped fresh flat-leaf parsley.",
      servings: 2,
      readyInMinutes: 15,
      cuisines: JSON.stringify(["Mediterranean"]),
      diets: JSON.stringify(["Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["lunch", "salad", "healthy"]),
      calories: 310,
      protein: 12,
      carbs: 28,
      fat: 16,
      fiber: 6,
      sugar: 4,
      ingredients: [
        { name: "Organic Chickpeas (Garbanzo)", amount: 1, unit: "can", aisle: "Canned Goods" },
        { name: "English Cucumber", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Organic Cherry Tomatoes", amount: 1, unit: "cup", aisle: "Produce" },
        { name: "Sheep's Milk Feta Cheese", amount: 60, unit: "grams", aisle: "Dairy" },
        { name: "Kalamata Olives", amount: 12, unit: "count", aisle: "Canned Goods" },
        { name: "Cold-Pressed Extra Virgin Olive Oil", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Lemon Juice", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Creamy Banana & Chia Oatmeal",
      summary: "A comforting, warm, and highly nutritious bowl of steel-cut oats cooked to a rich, creamy consistency in vanilla-infused organic almond milk. We top this warm oat base with sweet caramelized banana slices, nutrient-dense organic black chia seeds, a generous dusting of ground Ceylon cinnamon, and a light drizzle of pure organic maple syrup. This classic vegan breakfast is packed with soluble beta-glucan fiber, which helps regulate cholesterol levels, stabilize insulin response, and provide a steady, slow release of glucose for sustained energy throughout the morning.",
      image: null,
      instructions: "1. In a medium saucepan, bring the vanilla-infused almond milk and a pinch of salt to a gentle boil.\n2. Stir in the steel-cut or rolled oats. Reduce the heat to low and let simmer gently, stirring frequently to prevent sticking, for 7 to 8 minutes (or 20 minutes if using steel-cut) until the oats have absorbed the liquid and reached a thick, creamy consistency.\n3. While the oats are cooking, peel and slice the organic banana into rounds.\n4. Pour the hot, creamy oatmeal into a ceramic serving bowl.\n5. Artfully arrange the banana slices across the surface of the oats.\n6. Generously sprinkle the organic black chia seeds and ground Ceylon cinnamon over the banana and oats.\n7. Finish by drizzling a teaspoon of pure organic maple syrup over the bowl. Serve warm.",
      servings: 1,
      readyInMinutes: 10,
      cuisines: JSON.stringify(["American"]),
      diets: JSON.stringify(["Vegan", "Vegetarian"]),
      tags: JSON.stringify(["breakfast", "warm", "quick"]),
      calories: 290,
      protein: 9,
      carbs: 48,
      fat: 6,
      fiber: 10,
      sugar: 12,
      ingredients: [
        { name: "Organic Rolled Oats", amount: 0.5, unit: "cup", aisle: "Pantry" },
        { name: "Organic Banana", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Organic Black Chia Seeds", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Vanilla Almond Milk", amount: 1, unit: "cup", aisle: "Dairy Alternative" },
        { name: "Pure Organic Maple Syrup", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Ground Cinnamon", amount: 0.25, unit: "tsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Garlic Butter Shrimp Pasta",
      summary: "A savory, protein-packed Italian-inspired dinner featuring tender, wild-caught shrimp sautéed in a garlic-infused butter and organic extra virgin olive oil sauce. Tossed with al dente whole wheat spaghetti, fresh organic lemon zest, lemon juice, and a generous handful of finely chopped fresh flat-leaf parsley. This balanced dinner provides a rich source of lean seafood protein, essential selenium, and slow-digesting complex carbohydrates, offering a delicious, satisfying meal that satisfies gourmet cravings while respecting your health goals.",
      image: null,
      instructions: "1. Fill a large pot with water, add a generous pinch of sea salt, and bring to a rolling boil. Add the whole wheat spaghetti and cook for 9 to 10 minutes, stirring occasionally, until al dente. Reserve 1/4 cup of the starchy pasta water, then drain the spaghetti and set aside.\n2. Peel and devein the wild-caught shrimp, patting them completely dry with a paper towel. Mince the fresh garlic cloves.\n3. Melt the unsalted butter and olive oil together in a large skillet over medium heat. Add the minced garlic and sauté for 1 to 2 minutes until it becomes fragrant, taking care not to burn the garlic.\n4. Add the shrimp to the skillet in a single layer. Cook for 2 minutes on one side, then flip and cook for another 1 to 2 minutes until the shrimp turn pink and opaque. Do not overcook to keep them tender.\n5. Pour the cooked whole wheat spaghetti directly into the skillet with the shrimp and garlic butter. Add the fresh lemon zest, squeezed lemon juice, chopped flat-leaf parsley, and the reserved pasta cooking water.\n6. Toss everything together over low heat for 1 minute until the pasta is coated in a glossy garlic butter sauce. Season with fresh ground black pepper and red pepper flakes. Plate and serve immediately.",
      servings: 2,
      readyInMinutes: 20,
      cuisines: JSON.stringify(["Italian"]),
      diets: JSON.stringify(["High Protein"]),
      tags: JSON.stringify(["dinner", "pasta", "seafood"]),
      calories: 480,
      protein: 34,
      carbs: 52,
      fat: 14,
      fiber: 4,
      sugar: 2,
      ingredients: [
        { name: "Wild-Caught Shrimp", amount: 250, unit: "grams", aisle: "Seafood" },
        { name: "Whole Wheat Spaghetti", amount: 120, unit: "grams", aisle: "Pantry" },
        { name: "Fresh Garlic", amount: 4, unit: "cloves", aisle: "Produce" },
        { name: "Unsalted Grass-Fed Butter", amount: 1.5, unit: "tbsp", aisle: "Dairy" },
        { name: "Organic Extra Virgin Olive Oil", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Flat-Leaf Parsley", amount: 0.25, unit: "cup", aisle: "Produce" },
        { name: "Fresh Lemon", amount: 0.5, unit: "count", aisle: "Produce" },
      ],
    },
    {
      title: "Aromatic Red Lentil Coconut Curry",
      summary: "A rich, velvety, and deeply comforting red lentil curry simmered in a creamy, organic coconut milk base infused with fresh ginger, garlic, minced onions, and a warm blend of Indian spices including turmeric, cumin, coriander, and garam masala. Slowly simmered with diced tomatoes and finished with fresh baby spinach wilted into the stew. This nourishing vegan and gluten-free dish is loaded with dietary fiber, iron, folate, and plant-based protein, making it an exceptional choice for cellular rejuvenation and gut health.",
      image: null,
      instructions: "1. Heat a tablespoon of olive oil in a deep pot over medium heat. Add the finely chopped onion and sauté for 4 to 5 minutes until soft and translucent.\n2. Add the minced garlic and grated fresh ginger, stirring constantly for 1 minute. Add the curry powder, ground cumin, coriander, and turmeric, stirring for 30 seconds to toast the spices and release their essential oils.\n3. Rinse the dry red lentils in a fine mesh sieve. Add the lentils to the pot, followed by the canned diced tomatoes, vegetable broth, and coconut milk. Stir well to combine.\n4. Bring the curry to a boil, then reduce the heat to low, cover, and let simmer for 20 to 25 minutes, stirring occasionally, until the red lentils are soft and have thickened the gravy.\n5. Remove the lid, add the fresh baby spinach, and stir until the spinach is fully wilted.\n6. Squeeze fresh lime juice into the curry and stir. Serve hot in bowls garnished with fresh cilantro leaves.",
      servings: 3,
      readyInMinutes: 35,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegan", "Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "curry", "comfort-food"]),
      calories: 380,
      protein: 18,
      carbs: 45,
      fat: 12,
      fiber: 14,
      sugar: 5,
      ingredients: [
        { name: "Organic Dry Red Lentils", amount: 1, unit: "cup", aisle: "Pantry" },
        { name: "Organic Light Coconut Milk", amount: 1, unit: "can", aisle: "Canned Goods" },
        { name: "Organic Diced Tomatoes", amount: 1, unit: "can", aisle: "Canned Goods" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Curry Powder Blend", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Vegetable Broth", amount: 1.5, unit: "cups", aisle: "Pantry" },
        { name: "Organic Baby Spinach", amount: 2, unit: "cups", aisle: "Produce" },
        { name: "Fresh Ginger", amount: 1, unit: "tbsp", aisle: "Produce" },
        { name: "Fresh Garlic", amount: 3, unit: "cloves", aisle: "Produce" },
      ],
    },
    {
      title: "Turkey & Avocado Wrap",
      summary: "A fresh, clean, and macro-balanced wrap designed for busy individuals seeking high-quality lean protein and sustained energy without heavy digestion. Features premium deli-sliced roasted turkey breast rolled in a high-fiber whole wheat tortilla with fresh organic baby spinach, vine-ripened tomato slices, and a rich, creamy mash of organic Hass avocado. This easy wrap provides a healthy balance of lean proteins, dietary fiber, and healthy monounsaturated fats that stabilize energy levels and keep cravings away.",
      image: null,
      instructions: "1. Slice a fresh organic tomato into thin rounds. Wash and pat dry the baby spinach leaves.\n2. Cut half a ripe avocado, scoop the flesh into a bowl, and mash it with a fork. Mix in a squeeze of fresh lime juice and a pinch of salt to prevent browning and enhance flavor.\n3. Lay the high-fiber whole wheat tortilla flat on a clean cutting board.\n4. Using a spatula, spread the mashed avocado evenly across the surface of the tortilla, leaving a 1/2-inch border around the edges.\n5. Arrange the premium roasted turkey breast slices in a single layer over the avocado bed.\n6. Top the turkey with the tomato slices and a handful of organic baby spinach leaves.\n7. Carefully fold the left and right sides of the tortilla inward by about 1 inch, then roll the tortilla tightly from the bottom up.\n8. Cut the wrap diagonally in half and serve immediately.",
      servings: 1,
      readyInMinutes: 8,
      cuisines: JSON.stringify(["American"]),
      diets: JSON.stringify(["High Protein"]),
      tags: JSON.stringify(["lunch", "wrap", "quick"]),
      calories: 360,
      protein: 28,
      carbs: 22,
      fat: 18,
      fiber: 8,
      sugar: 1,
      ingredients: [
        { name: "High-Fiber Whole Wheat Tortilla", amount: 1, unit: "count", aisle: "Bakery" },
        { name: "Deli Roasted Turkey Breast", amount: 120, unit: "grams", aisle: "Meat" },
        { name: "Organic Hass Avocado", amount: 0.5, unit: "count", aisle: "Produce" },
        { name: "Organic Baby Spinach", amount: 0.5, unit: "cup", aisle: "Produce" },
        { name: "Organic Tomato", amount: 0.5, unit: "count", aisle: "Produce" },
      ],
    },
    {
      title: "High-Protein Egg Shakshuka",
      summary: "A traditional, deeply aromatic North African and Middle Eastern skillet dish featuring fresh organic eggs poached gently in a thick, rich reduction of diced tomatoes, red bell peppers, onions, and garlic. Spiced with ground cumin, smoked paprika, chili flakes, and fresh herbs, and topped with crumbled authentic Greek feta cheese. Naturally low-carb and gluten-free, this dish offers high-quality egg protein and powerful antioxidants (lycopene and Vitamin C) from the slow-cooked pepper-tomato sauce.",
      image: null,
      instructions: "1. Finely chop the yellow onion and dice the red bell pepper. Mince the fresh garlic cloves.\n2. Heat olive oil in a large skillet over medium heat. Add the onion and bell pepper, sautéing for 6 to 8 minutes until softened and lightly caramelized.\n3. Add the minced garlic, ground cumin, smoked paprika, and red pepper flakes, stirring constantly for 1 minute to release the aromas.\n4. Pour in the canned crushed tomatoes with their juices. Stir well and bring to a simmer. Reduce the heat to low and cook uncovered for 10 to 12 minutes until the tomato sauce has thickened.\n5. Use a large spoon to make 4 evenly spaced wells in the simmering tomato sauce. Crack an egg directly into each well.\n6. Cover the skillet with a tight-fitting lid and let cook over low heat for 6 to 8 minutes, or until the egg whites are fully set but the yolks remain soft and runny.\n7. Remove from the heat. Sprinkle the crumbled sheep's milk feta cheese and chopped fresh parsley over the skillet. Serve hot directly from the pan.",
      servings: 2,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Middle Eastern"]),
      diets: JSON.stringify(["Gluten Free"]),
      tags: JSON.stringify(["breakfast", "eggs", "spicy"]),
      calories: 270,
      protein: 16,
      carbs: 14,
      fat: 17,
      fiber: 3,
      sugar: 6,
      ingredients: [
        { name: "Organic Eggs", amount: 4, unit: "count", aisle: "Dairy" },
        { name: "Organic Crushed Tomatoes", amount: 1, unit: "can", aisle: "Canned Goods" },
        { name: "Organic Red Bell Pepper", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Organic Yellow Onion", amount: 0.5, unit: "count", aisle: "Produce" },
        { name: "Cold-Pressed Extra Virgin Olive Oil", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Ground Cumin", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Smoked Paprika", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Sheep's Milk Feta Cheese", amount: 40, unit: "grams", aisle: "Dairy" },
      ],
    },
    {
      title: "Paneer Butter Masala",
      summary: "A decadent, high-protein Indian classic featuring tender cubes of fresh paneer (cottage cheese) simmered in a smooth, aromatic gravy of slow-cooked vine-ripened tomatoes, sweet onions, ginger, garlic, and raw cashews. Finished with a touch of butter, garam masala, dried fenugreek leaves (kasuri methi), and fresh cream. This rich vegetarian dish is a staple of North Indian cuisine, providing complete dairy protein, calcium, and complex fats, making it a satisfying dinner that fuels energy and supports tissue health.",
      image: null,
      instructions: "1. Sauté chopped tomatoes, onions, ginger, garlic, and raw cashews in butter until soft. Let cool, then blend into a smooth paste.\n2. Heat butter and oil in a pan, add bay leaf, and pour in the blended gravy. Simmer on low heat for 10 minutes.\n3. Stir in Kashmiri red chili powder, garam masala, salt, and paneer cubes. Simmer for 3-4 minutes.\n4. Crush kasuri methi (dried fenugreek leaves) between your palms and sprinkle on top, stir in fresh cream, and garnish with fresh cilantro.",
      servings: 3,
      readyInMinutes: 30,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "High Protein", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "indian", "curry"]),
      calories: 420,
      protein: 18,
      carbs: 15,
      fat: 32,
      fiber: 3,
      sugar: 5,
      ingredients: [
        { name: "Fresh Paneer Cottage Cheese", amount: 250, unit: "grams", aisle: "Dairy" },
        { name: "Organic Vine Tomatoes", amount: 4, unit: "count", aisle: "Produce" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Raw Cashew Nuts", amount: 12, unit: "count", aisle: "Pantry" },
        { name: "Unsalted Grass-Fed Butter", amount: 2, unit: "tbsp", aisle: "Dairy" },
        { name: "Garam Masala Spice", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Kasuri Methi (Fenugreek)", amount: 1, unit: "tsp", aisle: "Pantry" },
        { name: "Heavy Cream", amount: 1, unit: "tbsp", aisle: "Dairy" },
      ],
    },
    {
      title: "Chicken Biryani",
      summary: "An iconic, celebratory Indian masterpiece showcasing tender, organic chicken thighs marinated in yogurt, garlic, ginger, and spices, layered with fragrant, long-grain basmati rice. Infused with saffron, caramelized onions (birista), fresh mint, cilantro, and warm whole spices like cardamom, cinnamon, cloves, and mace. Slowly cooked using the traditional 'dum' method to trap the aromatic vapors. This dish is a perfect protein-packed one-pot meal that provides robust flavors and energy.",
      image: null,
      instructions: "1. In a large bowl, combine the yogurt, ginger-garlic paste, red chili powder, turmeric, garam masala, lemon juice, and a pinch of salt. Add the chicken pieces, toss to coat, and let marinate in the refrigerator for at least 1 hour.\n2. Rinse the long-grain basmati rice under cold water until the water runs clear. Soak the rice in water for 30 minutes, then drain.\n3. Bring a large pot of water to a boil, add whole cloves, green cardamom, cinnamon stick, bay leaf, and salt. Add the soaked basmati rice and cook for 6 to 7 minutes until it is 70% cooked (still has a bite in the center). Drain the rice and set aside.\n4. Heat oil in a deep, heavy-bottomed pot. Add sliced onions and fry until they are a deep golden-brown (crispy fried onions or birista). Remove half of the onions for layering.\n5. In the same pot with the remaining onions, add the marinated chicken and cook over medium-high heat for 8 to 10 minutes until the chicken is seared and partially cooked through.\n6. Lower the heat. Spread the half-cooked chicken in an even layer at the bottom of the pot. Scatter fresh mint and cilantro leaves, followed by a layer of fried onions.\n7. Spread the parboiled basmati rice evenly over the chicken layer. Drizzle saffron-infused milk and melted ghee across the top of the rice. Scatter the remaining fried onions, fresh mint, and cilantro.\n8. Cover the pot with a tight-fitting lid or seal the edges with foil. Cook on low heat (dum) for 15 to 20 minutes until the chicken is tender and the rice is fluffy and fully cooked. Serve hot with raita.",
      servings: 4,
      readyInMinutes: 65,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["High Protein", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "indian", "rice"]),
      calories: 580,
      protein: 38,
      carbs: 64,
      fat: 18,
      fiber: 4,
      sugar: 2,
      ingredients: [
        { name: "Organic Chicken Thighs", amount: 500, unit: "grams", aisle: "Meat" },
        { name: "Premium Basmati Rice", amount: 2, unit: "cups", aisle: "Pantry" },
        { name: "Organic Plain Greek Yogurt", amount: 0.5, unit: "cup", aisle: "Dairy" },
        { name: "Organic Yellow Onions", amount: 2, unit: "count", aisle: "Produce" },
        { name: "Fresh Ginger Garlic Paste", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Mint & Cilantro Leaves", amount: 0.5, unit: "cup", aisle: "Produce" },
        { name: "Saffron Strands", amount: 6, unit: "count", aisle: "Pantry" },
        { name: "Pure Ghee (Clarified Butter)", amount: 2, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Yellow Lentil Tadka (Dal Tadka)",
      summary: "A comforting home-cooked Indian lentil curry made with split pigeon peas (toor dal), tempered with ghee, cumin seeds, garlic, red chilies, and fresh cilantro. Extremely rich in plant-based proteins and fiber, it is easily digestible and serves as a classic comforting meal.",
      image: null,
      instructions: "1. Rinse split peas thoroughly. Boil in water with turmeric and salt until soft and creamy.\n2. In a small pan, heat ghee or oil. Add cumin seeds and let them splutter.\n3. Add minced garlic, ginger, green chilies, and onions. Sauté until lightly browned.\n4. Add diced tomatoes, red chili powder, and cook until tomatoes are mushy.\n5. Pour this tempering (tadka) over the boiled lentils. Stir well, simmer for 2 minutes, and garnish with fresh cilantro.",
      servings: 3,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Vegan", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "lunch", "curry"]),
      calories: 240,
      protein: 12,
      carbs: 38,
      fat: 6,
      fiber: 8,
      sugar: 2,
      ingredients: [
        { name: "Organic Toor Dal (Yellow Split Peas)", amount: 150, unit: "grams", aisle: "Pantry" },
        { name: "Organic Vine Tomatoes", amount: 2, unit: "count", aisle: "Produce" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Fresh Garlic", amount: 4, unit: "cloves", aisle: "Produce" },
        { name: "Pure Ghee (or Mustard Oil)", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Cumin Seeds", amount: 1, unit: "tsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Spiced Chickpea Curry (Chana Masala)",
      summary: "A protein-rich and robust North Indian chickpea curry cooked in a tangy tomato-onion gravy spiced with coriander, cumin, and chana masala. Best enjoyed with basmati rice or hot whole wheat flatbreads.",
      image: null,
      instructions: "1. Heat oil in a pan, add finely chopped onions, and sauté until translucent.\n2. Add ginger-garlic paste and sauté for 1 minute.\n3. Stir in tomato puree, turmeric, chili powder, coriander, and chana masala powder. Sauté until oil separates from the spice mixture.\n4. Add drained cooked chickpeas and 1 cup of water. Cover and simmer on low heat for 15 minutes.\n5. Mash a few chickpeas with the back of a spoon to thicken the gravy. Garnish with ginger juliennes and fresh cilantro.",
      servings: 3,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Vegan", "Gluten Free"]),
      tags: JSON.stringify(["lunch", "dinner", "curry"]),
      calories: 280,
      protein: 11,
      carbs: 45,
      fat: 7,
      fiber: 10,
      sugar: 4,
      ingredients: [
        { name: "Organic Chickpeas (Canned/Boiled)", amount: 400, unit: "grams", aisle: "Canned Goods" },
        { name: "Organic Tomato Puree", amount: 1, unit: "cup", aisle: "Canned Goods" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Chana Masala Powder", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Olive Oil", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Aloo Gobi (Potato & Cauliflower)",
      summary: "A classic dry Indian curry made with cauliflower florets and tender potato cubes seasoned with turmeric, ginger, and green chilies. A healthy, simple, and satisfying vegetarian staple.",
      image: null,
      instructions: "1. Cut cauliflower into medium florets and potatoes into small cubes.\n2. Heat mustard oil or olive oil in a pan. Add cumin seeds and let them sizzle.\n3. Add finely chopped ginger and green chilies. Stir-fry for 30 seconds.\n4. Add potatoes and cauliflower, then stir in turmeric, coriander powder, and salt. Toss well to coat.\n5. Cover and cook on low heat for 15-20 minutes, stirring occasionally, until vegetables are tender. Garnish with fresh chopped cilantro.",
      servings: 3,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Vegan", "Gluten Free"]),
      tags: JSON.stringify(["lunch", "dinner", "side-dish"]),
      calories: 180,
      protein: 4,
      carbs: 28,
      fat: 6,
      fiber: 5,
      sugar: 3,
      ingredients: [
        { name: "Fresh Cauliflower", amount: 1, unit: "head", aisle: "Produce" },
        { name: "Organic Potatoes", amount: 2, unit: "count", aisle: "Produce" },
        { name: "Fresh Ginger", amount: 1, unit: "tbsp", aisle: "Produce" },
        { name: "Organic Olive Oil", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Spinach Cottage Cheese (Palak Paneer)",
      summary: "A highly nutritious green Indian curry featuring soft cottage cheese cubes simmered in a smooth, velvety, garlic-flavored spinach puree. Extremely rich in calcium, iron, and dairy protein.",
      image: null,
      instructions: "1. Blanch fresh spinach leaves in boiling water for 2 minutes, then plunge into ice water. Puree with green chilies.\n2. Heat ghee or oil in a pan, add cumin seeds, chopped garlic, and onions. Sauté until translucent.\n3. Stir in tomato paste, garam masala, and the spinach puree. Simmer on low for 5 minutes.\n4. Add fresh paneer cubes and let them absorb the flavors for 3 minutes.\n5. Stir in a splash of heavy cream, and serve warm with flatbreads.",
      servings: 3,
      readyInMinutes: 20,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Gluten Free", "High Protein"]),
      tags: JSON.stringify(["dinner", "lunch", "curry"]),
      calories: 320,
      protein: 16,
      carbs: 10,
      fat: 24,
      fiber: 4,
      sugar: 3,
      ingredients: [
        { name: "Fresh Paneer Cottage Cheese", amount: 200, unit: "grams", aisle: "Dairy" },
        { name: "Fresh Organic Spinach Leaves", amount: 300, unit: "grams", aisle: "Produce" },
        { name: "Fresh Garlic", amount: 4, unit: "cloves", aisle: "Produce" },
        { name: "Pure Ghee (Clarified Butter)", amount: 1, unit: "tbsp", aisle: "Pantry" },
        { name: "Heavy Cream", amount: 1, unit: "tbsp", aisle: "Dairy" },
      ],
    },
    {
      title: "Classic Butter Chicken (Murgh Makhani)",
      summary: "A globally beloved Indian chicken classic. Tender chicken chunks marinated in yogurt and spices are grilled, then simmered in a rich, buttery, velvety tomato gravy finished with fenugreek leaves and fresh cream.",
      image: null,
      instructions: "1. Marinate chicken breast chunks in yogurt, lemon juice, ginger-garlic paste, and garam masala for 30 minutes.\n2. Sauté chicken chunks in a pan until golden and cooked. Set aside.\n3. In the same pan, simmer tomato puree, onion paste, cashews, and butter until smooth. Blend if necessary to make a velvety gravy.\n4. Reintroduce the grilled chicken to the gravy. Simmer for 5 minutes.\n5. Sprinkle kasuri methi (fenugreek), stir in heavy cream, and serve with basmati rice.",
      servings: 3,
      readyInMinutes: 30,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["High Protein", "Gluten Free"]),
      tags: JSON.stringify(["dinner", "curry", "chicken"]),
      calories: 490,
      protein: 36,
      carbs: 12,
      fat: 33,
      fiber: 2,
      sugar: 4,
      ingredients: [
        { name: "Organic Boneless Chicken Breast", amount: 450, unit: "grams", aisle: "Meat" },
        { name: "Organic Tomato Puree", amount: 1.5, unit: "cups", aisle: "Canned Goods" },
        { name: "Unsalted Grass-Fed Butter", amount: 3, unit: "tbsp", aisle: "Dairy" },
        { name: "Heavy Cream", amount: 2, unit: "tbsp", aisle: "Dairy" },
        { name: "Raw Cashew Nuts", amount: 10, unit: "count", aisle: "Pantry" },
      ],
    },
    {
      title: "Tandoori Grilled Chicken Thighs",
      summary: "A lean and incredibly smoky grilled chicken marinated in a thick spiced yogurt mixture. Packed with protein, zero sugar, and grilled to juicy perfection.",
      image: null,
      instructions: "1. Make deep cuts in chicken thighs. Whisk yogurt, lemon juice, tandoori masala, salt, and ginger-garlic paste.\n2. Coat the chicken thoroughly in the marinade and refrigerate for 2 hours.\n3. Grill chicken thighs on a hot grill pan or outdoor grill for 8 minutes per side.\n4. Baste with a tiny touch of olive oil or ghee to keep it juicy.\n5. Serve hot garnished with onion rings, lemon wedges, and green chutney.",
      servings: 2,
      readyInMinutes: 25,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["High Protein", "Gluten Free"]),
      tags: JSON.stringify(["lunch", "dinner", "grilled"]),
      calories: 310,
      protein: 40,
      carbs: 4,
      fat: 14,
      fiber: 1,
      sugar: 2,
      ingredients: [
        { name: "Organic Chicken Thighs (Boneless)", amount: 350, unit: "grams", aisle: "Meat" },
        { name: "Organic Plain Greek Yogurt", amount: 0.5, unit: "cup", aisle: "Dairy" },
        { name: "Tandoori Masala Blend", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
        { name: "Fresh Ginger Garlic Paste", amount: 1, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Masala Egg Bhurji (Indian Scrambled Eggs)",
      summary: "A quick, fiery, and protein-packed Indian twist on scrambled eggs, loaded with chopped onions, sweet vine tomatoes, green chilies, and fresh coriander. A perfect 10-minute breakfast.",
      image: null,
      instructions: "1. Finely chop onion, tomato, green chili, and fresh coriander leaves.\n2. Whisk eggs in a bowl with a pinch of salt and turmeric powder.\n3. Melt butter in a skillet over medium heat. Sauté onion and chilies until translucent.\n4. Add tomatoes and sauté until soft. Pour in the whisked eggs.\n5. Stir constantly, scrambling the eggs over medium-low heat until cooked but still soft. Garnish with coriander.",
      servings: 2,
      readyInMinutes: 10,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["High Protein", "Gluten Free"]),
      tags: JSON.stringify(["breakfast", "eggs", "quick"]),
      calories: 220,
      protein: 14,
      carbs: 6,
      fat: 15,
      fiber: 2,
      sugar: 2,
      ingredients: [
        { name: "Organic Eggs", amount: 4, unit: "count", aisle: "Dairy" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Organic Vine Tomato", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Unsalted Grass-Fed Butter", amount: 1, unit: "tbsp", aisle: "Dairy" },
      ],
    },
    {
      title: "Basmati Rice Kheer (Sweet Rice Pudding)",
      summary: "A traditional, rich, and fragrant Indian rice dessert. Fragrant Basmati rice is slow-cooked in thickened whole milk, sweetened with sugar, and scented with cardamom, saffron strands, and chopped nuts.",
      image: null,
      instructions: "1. Wash and soak basmati rice in water for 30 minutes, then drain and crush slightly.\n2. Bring whole milk to a boil in a heavy-bottomed pot. Add the rice and simmer on low heat.\n3. Cook, stirring constantly to prevent burning, for 30-40 minutes until milk is reduced to half and rice is soft.\n4. Add sugar, cardamom powder, and saffron strands. Cook for another 5 minutes.\n5. Turn off heat, stir in sliced almonds and pistachios. Serve warm or chilled as a dessert.",
      servings: 4,
      readyInMinutes: 50,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["dessert", "sweet"]),
      calories: 260,
      protein: 6,
      carbs: 42,
      fat: 8,
      fiber: 0,
      sugar: 28,
      ingredients: [
        { name: "Basmati Rice", amount: 0.25, unit: "cup", aisle: "Pantry" },
        { name: "Whole Milk", amount: 4, unit: "cups", aisle: "Dairy" },
        { name: "Organic Cane Sugar", amount: 0.5, unit: "cup", aisle: "Pantry" },
        { name: "Saffron Strands", amount: 8, unit: "count", aisle: "Pantry" },
        { name: "Sliced Almonds & Pistachios", amount: 2, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Carrot Halwa (Gajar Ka Halwa)",
      summary: "An incredibly popular sweet dessert made with fresh grated carrots slow-cooked in milk, clarified butter (ghee), and sugar, studded with roasted cashews and raisins.",
      image: null,
      instructions: "1. Peel and finely grate fresh red or orange carrots.\n2. In a heavy pot, combine carrots and milk. Cook over medium-low heat, stirring, until all milk evaporates.\n3. Add ghee and sugar. Sauté the halwa on medium heat for 10-15 minutes until it turns a deep crimson.\n4. Add cardamom powder, and sauté for another 2 minutes.\n5. In a small pan, roast cashews and raisins in ghee and mix into the halwa. Serve warm.",
      servings: 4,
      readyInMinutes: 45,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["dessert", "sweet"]),
      calories: 290,
      protein: 5,
      carbs: 46,
      fat: 10,
      fiber: 3,
      sugar: 35,
      ingredients: [
        { name: "Fresh Grated Carrots", amount: 400, unit: "grams", aisle: "Produce" },
        { name: "Whole Milk", amount: 2, unit: "cups", aisle: "Dairy" },
        { name: "Pure Ghee (Clarified Butter)", amount: 2, unit: "tbsp", aisle: "Pantry" },
        { name: "Organic Cane Sugar", amount: 0.5, unit: "cup", aisle: "Pantry" },
      ],
    },
    {
      title: "Creamy Mango Lassi",
      summary: "A cooling and highly refreshing sweet Indian yogurt drink blended with fresh sweet mango pulp, milk, a pinch of cardamom, and a touch of honey.",
      image: null,
      instructions: "1. Peel and chop a sweet ripe mango, or use premium canned mango pulp.\n2. Add mango pulp, chilled plain yogurt, cold milk, cardamom powder, and honey into a blender.\n3. Blend on high speed for 1 minute until smooth, frothy, and creamy.\n4. Taste and add more honey if you prefer it sweeter.\n5. Pour into glasses, garnish with chopped pistachios or saffron strands, and serve chilled.",
      servings: 2,
      readyInMinutes: 5,
      cuisines: JSON.stringify(["Indian"]),
      diets: JSON.stringify(["Vegetarian", "Gluten Free"]),
      tags: JSON.stringify(["dessert", "drink", "sweet"]),
      calories: 190,
      protein: 5,
      carbs: 35,
      fat: 3,
      fiber: 2,
      sugar: 29,
      ingredients: [
        { name: "Ripe Mango Pulp", amount: 1, unit: "cup", aisle: "Produce" },
        { name: "Plain Greek Yogurt", amount: 1, unit: "cup", aisle: "Dairy" },
        { name: "Whole Milk", amount: 0.5, unit: "cup", aisle: "Dairy" },
        { name: "Raw Honey", amount: 1, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Chia Chocolate Pudding",
      summary: "A healthy, guilt-free chocolate dessert pudding packed with fiber, healthy omega-3 fats, and rich cocoa flavor. Made with chia seeds swelled in cocoa-infused almond milk.",
      image: null,
      instructions: "1. In a bowl, whisk together cocoa powder, vanilla extract, and maple syrup.\n2. Slowly pour in almond milk, whisking continuously until cocoa is completely dissolved.\n3. Stir in the chia seeds. Let sit for 5 minutes, then stir again to break up any clumps.\n4. Cover the bowl and refrigerate for at least 4 hours (or overnight) until thick and gelatinous.\n5. Stir before serving. Spoon into cups and top with fresh raspberries or dark chocolate shavings.",
      servings: 2,
      readyInMinutes: 10,
      cuisines: JSON.stringify(["Global"]),
      diets: JSON.stringify(["Vegetarian", "Vegan", "Gluten Free"]),
      tags: JSON.stringify(["dessert", "sweet", "healthy"]),
      calories: 180,
      protein: 4,
      carbs: 18,
      fat: 10,
      fiber: 8,
      sugar: 8,
      ingredients: [
        { name: "Organic Chia Seeds", amount: 0.25, unit: "cup", aisle: "Pantry" },
        { name: "Unsweetened Cocoa Powder", amount: 2, unit: "tbsp", aisle: "Pantry" },
        { name: "Vanilla Almond Milk", amount: 1, unit: "cup", aisle: "Dairy Alternative" },
        { name: "Pure Maple Syrup", amount: 1.5, unit: "tbsp", aisle: "Pantry" },
      ],
    },
    {
      title: "Vegetarian Black Bean Quesadillas",
      summary: "A simple, crispy, and delicious Mexican favorite. Tortillas are filled with a high-fiber mixture of black beans, sweet corn, salsa, spices, and melted cheddar, then toasted on a skillet.",
      image: null,
      instructions: "1. In a bowl, mix drained black beans, canned corn, taco spices, and salsa.\n2. Lay a tortilla flat, spread the bean mix on one half, and scatter a handful of cheddar cheese.\n3. Fold the tortilla over to close. Repeat for the other tortillas.\n4. Heat a touch of olive oil in a skillet. Sear the quesadilla for 3 minutes per side until crispy and cheese melts.\n5. Slice into wedges and serve with sour cream or fresh guacamole.",
      servings: 2,
      readyInMinutes: 15,
      cuisines: JSON.stringify(["Mexican"]),
      diets: JSON.stringify(["Vegetarian"]),
      tags: JSON.stringify(["lunch", "quick", "mexican"]),
      calories: 380,
      protein: 16,
      carbs: 44,
      fat: 14,
      fiber: 8,
      sugar: 2,
      ingredients: [
        { name: "Whole Wheat Tortillas", amount: 2, unit: "count", aisle: "Bakery" },
        { name: "Canned Black Beans", amount: 1, unit: "cup", aisle: "Canned Goods" },
        { name: "Sweet Corn Kernels", amount: 0.5, unit: "cup", aisle: "Canned Goods" },
        { name: "Shredded Cheddar Cheese", amount: 60, unit: "grams", aisle: "Dairy" },
      ],
    },
    {
      title: "Classic Chicken Fajitas",
      summary: "A high-protein Mexican restaurant style sizzler. Thinly sliced chicken breast sautéed with colorful bell peppers and red onions in fajita spices. Served with warm tortillas.",
      image: null,
      instructions: "1. Slice chicken breast, bell peppers, and onions into thin, uniform strips.\n2. Toss chicken and veggies in olive oil, cumin, chili powder, garlic, salt, and lime juice.\n3. Heat a large heavy skillet on high. Add chicken and cook for 5 minutes until browned.\n4. Throw in peppers and onions. Stir-fry rapidly for 4 minutes until veggies are tender-crisp.\n5. Serve hot wrapped in warm flour tortillas with fresh limes.",
      servings: 2,
      readyInMinutes: 20,
      cuisines: JSON.stringify(["Mexican"]),
      diets: JSON.stringify(["High Protein"]),
      tags: JSON.stringify(["dinner", "lunch", "mexican"]),
      calories: 410,
      protein: 38,
      carbs: 18,
      fat: 20,
      fiber: 3,
      sugar: 3,
      ingredients: [
        { name: "Organic Boneless Chicken Breast", amount: 300, unit: "grams", aisle: "Meat" },
        { name: "Red & Green Bell Peppers", amount: 2, unit: "count", aisle: "Produce" },
        { name: "Organic Yellow Onion", amount: 1, unit: "count", aisle: "Produce" },
        { name: "Whole Wheat Flour Tortillas", amount: 4, unit: "count", aisle: "Bakery" },
      ],
    },
  ];

  for (const recipe of recipesData) {
    const createdRecipe = await prisma.recipe.create({
      data: {
        title: recipe.title,
        summary: recipe.summary,
        image: recipe.image,
        instructions: recipe.instructions,
        servings: recipe.servings,
        readyInMinutes: recipe.readyInMinutes,
        cuisines: recipe.cuisines,
        diets: recipe.diets,
        tags: recipe.tags,
        calories: recipe.calories,
        protein: recipe.protein,
        carbs: recipe.carbs,
        fat: recipe.fat,
        fiber: recipe.fiber,
        sugar: recipe.sugar,
        isCustom: false,
      },
    });

    for (const ing of recipe.ingredients) {
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.name },
        update: { aisle: ing.aisle },
        create: { name: ing.name, aisle: ing.aisle },
      });

      await prisma.recipeIngredient.create({
        data: {
          recipeId: createdRecipe.id,
          ingredientId: ingredient.id,
          amount: ing.amount,
          unit: ing.unit,
          original: `${ing.amount} ${ing.unit} of ${ing.name}`,
        },
      });
    }
  }

  console.log("Database successfully seeded with default recipes!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
